@echo off
md "[1] Python I\[1] Getting Started with Python"
break>"[1] Python I\[1] Getting Started with Python\1. Getting Started.py"
md "[1] Python I\[2] The Basics"
break>"[1] Python I\[2] The Basics\2. Strings.py"
break>"[1] Python I\[2] The Basics\3. Integers.py"
break>"[1] Python I\[2] The Basics\4. Calculations.py"
md "[1] Python I\[3] Variables"
break>"[1] Python I\[3] Variables\5. Variables.py"
break>"[1] Python I\[3] Variables\6. Using Variables.py"
break>"[1] Python I\[3] Variables\7. Updating Variables.py"
break>"[1] Python I\[3] Variables\8. String Concatenation.py"
break>"[1] Python I\[3] Variables\9. Data Types.py"
md "[1] Python I\[4] Booleans and Conditions"
break>"[1] Python I\[4] Booleans and Conditions\10. if Statements.py"
break>"[1] Python I\[4] Booleans and Conditions\11. Booleans.py"
break>"[1] Python I\[4] Booleans and Conditions\12. else Statements.py"
break>"[1] Python I\[4] Booleans and Conditions\13. elif Statements.py"
break>"[1] Python I\[4] Booleans and Conditions\14. Combining Conditions.py"
md "[1] Python I\[5] The Shopping App"
break>"[1] Python I\[5] The Shopping App\15. Calculating Prices.py"
break>"[1] Python I\[5] The Shopping App\16. Getting Input.py"
break>"[1] Python I\[5] The Shopping App\17. Control Flow.py"
md "[2] Python II\[1] Getting Started"
break>"[2] Python II\[1] Getting Started\1. Getting Started.py"
md "[2] Python II\[2] Structuring Data"
break>"[2] Python II\[2] Structuring Data\2. Lists.py"
break>"[2] Python II\[2] Structuring Data\3. Adding and Updating List Elements.py"
break>"[2] Python II\[2] Structuring Data\4. For Loops.py"
break>"[2] Python II\[2] Structuring Data\5. Dictionaries.py"
break>"[2] Python II\[2] Structuring Data\6. Adding and Updating Dictionary Elements.py"
break>"[2] Python II\[2] Structuring Data\7. For Loops (2).py"
md "[2] Python II\[3] Working with Loops"
break>"[2] Python II\[3] Working with Loops\8. While Loops.py"
break>"[2] Python II\[3] Working with Loops\9. Break Statements.py"
break>"[2] Python II\[3] Working with Loops\10. Continue Statements.py"
md "[2] Python II\[4] The Shopping App"
break>"[2] Python II\[4] The Shopping App\11. Preparing the Items.py"
break>"[2] Python II\[4] The Shopping App\12. Buying an Item.py"
break>"[2] Python II\[4] The Shopping App\13. Control Flow.py"
break>"[2] Python II\[4] The Shopping App\14. The Remaining Money.py"
md "[3] Python III\[1] Getting Started"
break>"[3] Python III\[1] Getting Started\1. Getting Started.py"
md "[3] Python III\[2] Functions"
break>"[3] Python III\[2] Functions\2. Functions.py"
break>"[3] Python III\[2] Functions\3. Parameters and Arguments.py"
break>"[3] Python III\[2] Functions\4. Multiple Parameters.py"
break>"[3] Python III\[2] Functions\5. Default Parameter Values.py"
md "[3] Python III\[3] Rock Paper Scissors App"
break>"[3] Python III\[3] Rock Paper Scissors App\6. Getting Input.py"
break>"[3] Python III\[3] Rock Paper Scissors App\7. Picking a Hand.py"
break>"[3] Python III\[3] Rock Paper Scissors App\8. Return Value.py"
break>"[3] Python III\[3] Rock Paper Scissors App\9. Return.py"
md "[3] Python III\[4] Rock Paper Scissors App (2)"
break>"[3] Python III\[4] Rock Paper Scissors App (2)\10. Adding the Computer.py"
break>"[3] Python III\[4] Rock Paper Scissors App (2)\11. Judging the Winner.py"
break>"[3] Python III\[4] Rock Paper Scissors App (2)\12. Using Modules.py"
break>"[3] Python III\[4] Rock Paper Scissors App (2)\13. Python Standard Library.py"
break>"[3] Python III\[4] Rock Paper Scissors App (2)\12. Buying an Item.py"
break>"[3] Python III\[4] Rock Paper Scissors App (2)\13. Control Flow.py"
md "[4] Python IV\[1] Classes and Instances"
break>"[4] Python IV\[1] Classes and Instances\1. Overview.py"
break>"[4] Python IV\[1] Classes and Instances\2. Class Definitions.py"
break>"[4] Python IV\[1] Classes and Instances\3. Class Instantiation.py"
break>"[4] Python IV\[1] Classes and Instances\4. Instance Variables.py"
break>"[4] Python IV\[1] Classes and Instances\5. Multiple Instances.py"
md "[4] Python IV\[2] Instance Methods"
break>"[4] Python IV\[2] Instance Methods\6. Classes and Methods.py"
break>"[4] Python IV\[2] Instance Methods\7. Instance Methods: self.py"
break>"[4] Python IV\[2] Instance Methods\8. Instance Methods: Return Values.py"
break>"[4] Python IV\[2] Instance Methods\9. Instance Methods: Parameters.py"
break>"[4] Python IV\[2] Instance Methods\10. The __init__ Method (1).py"
break>"[4] Python IV\[2] Instance Methods\11. The __init__ Method (2).py"
break>"[4] Python IV\[2] Instance Methods\12. The __init__ Method (3).py"
md "[4] Python IV\[3] The Food Ordering System"
break>"[4] Python IV\[3] The Food Ordering System\13. File Separation.py"
break>"[4] Python IV\[3] The Food Ordering System\14. Displaying the Menu (1).py"
break>"[4] Python IV\[3] The Food Ordering System\15. Displaying the Menu (2).py"
break>"[4] Python IV\[3] The Food Ordering System\16. Handling Input.py"
break>"[4] Python IV\[3] The Food Ordering System\17. Calculating the Total Amount.py"
md "[5] Python V\[1] Class Inheritance"
break>"[5] Python V\[1] Class Inheritance\1. Overview.py"
break>"[5] Python V\[1] Class Inheritance\2. What is Inheritance?.py"
break>"[5] Python V\[1] Class Inheritance\3. How Inheritance Works.py"
break>"[5] Python V\[1] Class Inheritance\4. Adding Instance Methods.py"
break>"[5] Python V\[1] Class Inheritance\5. Revising the info Method (1).py"
break>"[5] Python V\[1] Class Inheritance\6. Revising the info Method (2).py"
break>"[5] Python V\[1] Class Inheritance\7. Overriding the __init__ Method.py"
break>"[5] Python V\[1] Class Inheritance\8. super().py"
break>"[5] Python V\[1] Class Inheritance\9. Review of Overriding.py"
break>"[5] Python V\[1] Class Inheritance\10. Practical Application.py"
